server:
  port: 9001
  
spring:
  data:
    cassandra:
     port: 9042
     keyspace-name: container_yard
url : http://localhost:9001/api/bookings
#url : https://www.maersk.com/api/bookings/checkAvailable